version: '2'
services:
  connect:
    image: debezium:${DEBEZIUM_VERSION}
    build:
      context: ./
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
      - 5005:5005
    environment:
      - BOOTSTRAP_SERVERS=${KAFKA_HOST}:${KAFKA_PORT}
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=oracle_connect_configs
      - OFFSET_STORAGE_TOPIC=oracle_connect_offsets
      - STATUS_STORAGE_TOPIC=oracle_connect_statuses
      - OFFSET_FLUSH_INTERVAL_MS=10000
      - OFFSET_FLUSH_TIMEOUT_MS=3000
      - SHUTDOWN_TIMEOUT=5000
      - HEAP_OPTS="-Xms256M -Xmx2G"
      - CONNECT__HEARTBEAT_INTERVAL_MS=1000
